server:
  error:
    whitelabel:
      enabled: true
    include-message: always

  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/carcli
    username: nocli
    password: Tri2107@

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: false

  main:
    web-application-type: servlet